version: '3.5'

services:
  front_end:
    image: fr-end
    ports:
      - 5000:5000
    container_name: "front_end"

  back_end:
    image: b-end
    ports:
      - 8000:8000
    volumes:
      - ./host_logs.txt:/mydir/logs.txt
    container_name: "back_end"
    environment:
      - REDIS=redis
      - REDIS_PORT=6379

  redis:
    image: redis
    ports:
      - 6379:6379
