version: '3.5'

services:
  front_end:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5000:5000"
    container_name: "front_end"

  back_end:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./host_logs.txt:/mydir/logs.txt
    container_name: "back_end"
